# Start with docker-compose -f docker-compose-dev.yaml up -d

version: "3.8"

services:
  frontend:
    ports:
      - "25000:5000"
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    command: tail -F anything
    volumes:
      - ./frontend:/opt/app
    depends_on:
      - hasura
      - keycloak
  
  hasura:
    image: hasura/graphql-engine:v2.0.3.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - db_hasura
      - keycloak
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@db_hasura:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "key": "-----BEGIN CERTIFICATE-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjA2VMVrXYPs6+wRCq4Hh5eADoiKrBAV7KymVoO3JTWMM2QWe/HKLivToU9f3oTc66HZmY9pwTbpDf7OCI1XpzVMJAVnJDaw/LvcGynKc36geUFG8eBrgMIZoMo3E4OQvz+GNZ4rFQB20cTEWBn/F7TLZz3XOSFK0TUMV3GYTFT9AnS3mbkA1LBneqZn0t3o9QBjHXGvvhOYCuzQ3oXvmmPSAc7v/Vg7l77FNIgX5ckmBQ/62940dpmo1XFRXW9V0U+OU5NOqoQofXnD6XvOasviZgtJBqmN1pK8p8JVONJZEwuAafY/XqmsWyp3XAsHgWiZx3ipKTe8fTxLdcZplyQIDAQAB\n-----END CERTIFICATE-----"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_CLOUD_FUNCTION_SECRET: "${HASURA_CLOUD_FUNCTION_SECRET}"
      HASURA_BUCKET: "${HASURA_BUCKET}"
      CLOUD_FUNCTION_LINK: "https://europe-west3-edu-hub-staging.cloudfunctions.net"
    volumes:
      - ./backend/migrations:/hasura-migrations
      - ./backend/metadata:/hasura-metadata
      - ./backend/seeds:/hasura-seeds

  db_hasura:
    image: postgres:12
    volumes:
      - db_hasura_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  keycloak:
    build: ./keycloak
    ports:
      - 28080:8080
    depends_on:
      - db_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: db_keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /imports/edu-hub-realm.json
    volumes:
      - ./keycloak/imports:/imports

  db_keycloak:
    image: postgres:12
    volumes:
      - db_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

volumes:
  db_hasura_data:
  db_keycloak_data:
