name: edu-plattform-mvp
region: fra

services:
  - name: frontend
    dockerfile_path: frontend/Dockerfile
    github:
      repo: opencampus-sh/edu-plattform-mvp
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    source_dir: frontend
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs

databases:
  - name: db-dev
    engine: PG
    version: "12"
    production: false
    db_name: db-dev
    db_user: db-dev
