name: edu-plattform
region: fra

services:
  - name: frontend
    dockerfile_path: frontend/Dockerfile
    github:
      repo: opencampus-sh/edu-plattform
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    source_dir: frontend
    http_port: 25000
    instance_count: 1
    instance_size_slug: basic-s

databases:
  - name: db
    engine: PG
    version: "12"
    production: true
    db_name: db
    db_user: db
