name: edu-plattform-mvp

services:
  - name: frontend
    dockerfile_path: Dockerfile
    github:
      repo: opencampus-sh/edu-plattform-mvp
      branch: main
      deploy_on_push: true
    source_dir: frontend
