table:
  name: AppSettings
  schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - appName
        - backgroundImageURL
        - bannerBackgroundColor
        - bannerFontColor
        - bannerTextDe
        - bannerTextEn
        - created_at
        - previewImageURL
        - updated_at
      filter: {}
