name: Build and Store a Docker Image in the Artifact Registry

on:
  workflow_call:
    inputs:
      # Name of the branch that triggered the workflow run
      BRANCH:
        required: true
        type: string
      # ID of the project in Google in which the image will be stored and deployed
      PROJECT_ID:
        required: true
        type: string
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true
      GCP_REGION:
        required: true


jobs:

  build-keycloak:
    name: Build Docker Image for Keycloak and save to the Google Docker repo
    uses: ./.github/workflows/build-docker-image.yml
    with:
      # Folder with the Dockerfile that is used for creating the image
      DOCKERFILE_FOLDER: keycloak
      # Name for the docker image
      IMAGE_NAME: keycloak
      # Name of the branch that triggered the workflow run
      BRANCH: ${{ inputs.BRANCH }}
      # ID of the project in Google in which the image will be stored and deployed
      PROJECT_ID: ${{ inputs.PROJECT_ID }}
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_STAGING }}
      GCP_REGION: ${{ secrets.GCP_REGION }}

  # build-backend:
  #   name: Build Docker Image for the bacjend (Hasura) and save to the Google Docker repo
  #   uses: ./.github/workflows/build-docker-image.yml
  #   with:
  #     # Folder with the Dockerfile that is used for creating the image
  #     DOCKERFILE_FOLDER: backend
  #     # Name for the docker image
  #     IMAGE_NAME: backend
  #     # Name of the branch that triggered the workflow run
  #     BRANCH: ${{ inputs.BRANCH }}
  #     # ID of the project in Google in which the image will be stored and deployed
  #     PROJECT_ID: ${{ inputs.PROJECT_ID }}
  #   secrets:
  #     GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_STAGING }}
  #     GCP_REGION: ${{ secrets.GCP_REGION }}

  # build-frontend:
  #   name: Build Docker Image for the frontend and save to the Google Docker repo
  #   uses: ./.github/workflows/build-docker-image.yml
  #   with:
  #     # Folder with the Dockerfile that is used for creating the image
  #     DOCKERFILE_FOLDER: frontend
  #     # Name for the docker image
  #     IMAGE_NAME: frontend
  #     # Name of the branch that triggered the workflow run
  #     BRANCH: ${{ inputs.BRANCH }}
  #     # ID of the project in Google in which the image will be stored and deployed
  #     PROJECT_ID: ${{ inputs.PROJECT_ID }}
  #   secrets:
  #     GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_STAGING }}
  #     GCP_REGION: ${{ secrets.GCP_REGION }}
