name: Setup Staging Environment
on:   
  push:
    # Run only on changes in the following branches
    branches:
      - develop

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  pull_request:
    # Run tests for PRs.
    branches:
      - staging

env:
  TF_WORKSPACE: eduhub-application-staging

jobs:

  build-backend:
    name: Build and Store Backend Docker Image in Google Docker Repo
    uses: ./.github/workflows/build-and-store-docker-image.yml
    with:
      DOCKERFILE_FOLDER: backend
      IMAGE_NAME: backend
      BRANCH: ${{ github.ref_name }}
      PROJECT_ID: eduhub-staging-new
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_EDUHUB_STAGING_KEY }}
      GCP_REGION: ${{ secrets.GCP_REGION }}

