name: Setup Staging Environment
on:   
  push:
    # Run only on changes in the following branches
    branches:
      - feature/image_update_automation

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*


env:
  PROJECT_ID: eduhub-staging-new
  TF_WORKSPACE: eduhub-application-staging
  TF_WORKSPACE_ID: ws-wVwkztBCRbphphYw
  TF_VAR_ID_COMMIT_SHA: var-sSiBMg7YBPL7NcFh

jobs:

  save-commit-sha:  
    if: github.event_name == 'pull_request'
    name: Save SHA of current commit in Terraform Cloud
    runs-on: ubuntu-latest
    steps:
      -
        name: Check Out the Repository Branch
        uses: actions/checkout@v2
      -
        name: Save commit SHA in Terraform Cloud variable
        run: |
          curl \
          --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request PATCH \
          --data "{ \"data\": { \"id\":\"$TF_VAR_ID_COMMIT_SHA\", \"attributes\": { \"value\":\"$GITHUB_SHA\" }, \"type\":\"vars\" }}" \
          https://app.terraform.io/api/v2/workspaces/$TF_WORKSPACE_ID/vars/$TF_VAR_ID_COMMIT_SHA


  # build-backend:
  #   name: Build and Store Backend Docker Image in Google Docker Repo
  #   uses: ./.github/workflows/build-and-store-docker-image.yml
  #   with:
  #     DOCKERFILE_FOLDER: backend
  #     IMAGE_NAME: backend
  #     BRANCH: ${{ github.ref_name }}
  #     PROJECT_ID: $PROJECT_ID
  #     TF_WORKSPACE_ID: ws-wVwkztBCRbphphYw
  #     TF_VAR_ID_COMMIT_SHA: var-sSiBMg7YBPL7NcFh
  #   secrets:
  #     GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_EDUHUB_STAGING_KEY }}
  #     GCP_REGION: ${{ secrets.GCP_REGION }}
  #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

